/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.navaile.enigma4k;

/**
 *
 * @author vladpaln
 */
public class AboutDialog extends javax.swing.JDialog {
	
	private static String about =
		"Parameters - Both parties must have this information.\n" +
		"Rotor #: Number of rotors.\n" +
		"Plugboard #: Number of plugboards.\n" +
		"Recipient: Recipient email or online handle. Used to encrypt message.\n" +
		"Crypt Phrase: A pass phrase used to encrypt/decrypt text.\n" +
		"Text - Plain text to be encrypted or crypt text to be decrypted.\n" +
		
		"Additional Parameters - For increased security.\n" +
		"Directory Seed: Used to randomize directory. Default is blank.\n" +

		"About Enigma 4K\n" +
		"Enigma 4K is based on the original with several improvements. The number\n" +
		"of rotors and plugboards can now be set to any value between 97 and 4K.\n" +
		"The only limitation is system memory that holds all of the rotors and\n" +
		"plugboard data. The reflector has also been removed and rotors now have\n" +
		"46,655 values.\n\n" +

		"Features\n" +
		"- each message will have a different seed\n" +
		"- no reflector, value can map to itself\n" +
		"- random step size for each rotor\n" +
		"- random direction rotor rotation\n\n" +

		"How Enigma 4K Works\n" +
		"Enigma 4K encryption starts by first encoding plain text into its numeric\n" +
		"equivalent, but instead of encoding letters, Enigma 4K encodes entire\n" +
		"words. Next a seed is generated using the pass phrase and email/handle.\n" +
		"Use of email/handle is highly recommended to avoid cracking using common\n" +
		"pass phrases. The generated seed is used to spawn random rotors, plugboards,\n" +
		"rotor step direction, and rotor step size. The encoded value is passed\n" +
		"through a plugboards => rotors sequence multiple times before converting\n" +
		"the final value to base36 text.\n\n";

	/**
	 * Creates new form AboutDialog
	 */
	public AboutDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		if(aboutPane != null) {
			aboutPane.setText(about);
			aboutPane.setCaretPosition(0);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Enigma 4K");

        closeButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        aboutPane.setEditable(false);
        aboutPane.setBackground(new java.awt.Color(240, 240, 240));
        aboutPane.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(aboutPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 700, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane aboutPane;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
