/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.navaile.enigma4k;

import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.JTextComponent;
import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author vladpaln
 */
public class EnigmaGUI extends javax.swing.JFrame {

	/**
	 * Creates new form EnigmaGUI
	 */
	public EnigmaGUI() {
		initComponents();
		
		if(jScrollPane1 != null)
			jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		
		if(textField != null)
			textField.setWrapStyleWord(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        roLabel = new javax.swing.JLabel();
        pbLabel = new javax.swing.JLabel();
        handleLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textField = new javax.swing.JTextArea();
        encryptButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        handleField = new javax.swing.JTextField();
        pbCountField = new javax.swing.JTextField();
        roCountField = new javax.swing.JTextField();
        textDescLabel = new javax.swing.JLabel();
        dirSeedLabel = new javax.swing.JLabel();
        dirSeedField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enigma 4K");
        setPreferredSize(new java.awt.Dimension(1080, 720));

        title.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        title.setText("Enigma 4K");

        roLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        roLabel.setText("Rotor #");

        pbLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pbLabel.setText("Plugboard #");

        handleLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        handleLabel.setText("Recipient");

        passLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        passLabel.setText("Crypt Phrase");

        textLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        textLabel.setText("Text");

        textField.setColumns(20);
        textField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        textField.setLineWrap(true);
        textField.setRows(5);
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(textField);

        encryptButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        encryptButton.setText("Encrypt");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        decryptButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        decryptButton.setText("Decrypt");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });

        handleField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        handleField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                handleFieldFocusGained(evt);
            }
        });

        pbCountField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pbCountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pbCountField.setText("97");
        pbCountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pbCountFieldFocusGained(evt);
            }
        });

        roCountField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        roCountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        roCountField.setText("97");
        roCountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roCountFieldFocusGained(evt);
            }
        });

        textDescLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textDescLabel.setText("(allowed chars: A-Za-z, 0-9, standard punctuation)");

        dirSeedLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dirSeedLabel.setText("Directory Seed");

        dirSeedField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dirSeedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dirSeedFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encryptButton)
                        .addGap(18, 18, 18)
                        .addComponent(decryptButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textLabel)
                        .addGap(18, 18, 18)
                        .addComponent(textDescLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbLabel)
                            .addComponent(roLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dirSeedLabel)
                                .addGap(251, 251, 251))
                            .addComponent(dirSeedField)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(handleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(handleField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(passwordField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roLabel)
                    .addComponent(roCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirSeedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbLabel)
                    .addComponent(pbCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirSeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(handleLabel)
                    .addComponent(handleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel)
                    .addComponent(textDescLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptButton)
                    .addComponent(decryptButton)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed

		String passPhrase = passwordField.getText();
		String handle = handleField.getText();
		String roCountText = roCountField.getText();
		String pbCountText = pbCountField.getText();
		String dirSeedText = dirSeedField.getText();
		
		int roCount = 97, pbCount = 97;
		Long dirSeed = null;

		if(roCountText.length() != 0)
			try {	roCount = Integer.parseInt(roCountText);				}
			catch(Exception e) {	System.err.println(e);					}
		
		if(pbCountText.length() != 0)
			try {	pbCount = Integer.parseInt(pbCountText);				}
			catch(Exception e) {	System.err.println(e);					}
		
		if(dirSeedText.length() != 0)	
			try {	dirSeed = Long.parseLong(dirSeedText);					}
			catch(Exception e) {	System.err.println(e);					}
		
		try {
			textField.setText(Enigma4K.encryptText(passPhrase, handle, roCount,
					pbCount, dirSeed, textField.getText()));
		}
		catch(Exception e) {	System.err.println(e);						}	
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
		
		String passPhrase = passwordField.getText();
		String handle = handleField.getText();
		String roCountText = roCountField.getText();
		String pbCountText = pbCountField.getText();
		String dirSeedText = dirSeedField.getText();
		
		int roCount = 97, pbCount = 97;
		Long dirSeed = null;

		if(roCountText.length() != 0)
			try {	roCount = Integer.parseInt(roCountText);				}
			catch(Exception e) {	System.err.println(e);					}
		
		if(pbCountText.length() != 0)
			try {	pbCount = Integer.parseInt(pbCountText);				}
			catch(Exception e) {	System.err.println(e);					}
		
		if(dirSeedText.length() != 0)	
			try {	dirSeed = Long.parseLong(dirSeedText);					}
			catch(Exception e) {	System.err.println(e);					}
		
		try {
			textField.setText(Enigma4K.decryptText(passPhrase, handle, roCount,
					pbCount, dirSeed, textField.getText()));
		}
		catch(Exception e) {	System.err.println(e);						}
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

		roCountField.setText("97");
		pbCountField.setText("97");
		handleField.setText("");
		passwordField.setText("");
		dirSeedField.setText("");
		textField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void roCountFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roCountFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_roCountFieldFocusGained

    private void pbCountFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pbCountFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_pbCountFieldFocusGained

    private void handleFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_handleFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_handleFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_passwordFieldFocusGained

    private void dirSeedFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dirSeedFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_dirSeedFieldFocusGained

    private void textFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFocusGained
		focusGained(evt);
    }//GEN-LAST:event_textFieldFocusGained

	public void focusGained(java.awt.event.FocusEvent evt) {
		
		if(evt.getSource() instanceof JTextComponent)
			SwingUtilities.invokeLater(new Runnable() {
				@Override
				public void run() {
					((JTextComponent) evt.getSource()).selectAll();
				}
			});
    }
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		BasicConfigurator.configure();
		Logger.getRootLogger().setLevel(Level.ERROR);

		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		try {
			
			/* Set look and feel */
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		}
		catch(Exception ex) {
			java.util.logging.Logger.getLogger(EnigmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EnigmaGUI().setVisible(true);
			}
		});
	}
	
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decryptButton;
    private javax.swing.JTextField dirSeedField;
    private javax.swing.JLabel dirSeedLabel;
    private javax.swing.JButton encryptButton;
    private javax.swing.JTextField handleField;
    private javax.swing.JLabel handleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField pbCountField;
    private javax.swing.JLabel pbLabel;
    private javax.swing.JTextField roCountField;
    private javax.swing.JLabel roLabel;
    private javax.swing.JLabel textDescLabel;
    private javax.swing.JTextArea textField;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
